import { useState, type ChangeEvent, type DragEvent, type ReactNode } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, FileText, Paperclip, Printer, ShieldCheck, Trash2, UploadCloud } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { CitizenProfile } from "@/lib/api";
import type { CitizenComplaint } from "@/components/CitizenDashboard";

type EvidenceFile = { id: string; name: string; type: string; size: string; status: "Uploaded" };
type ComplaintDraft = {
  incidentDate: string; incidentTime: string; fraudType: string; fraudMethod: string; incidentDescription: string;
  transactionId: string; transactionDate: string; transactionTime: string; amount: string; bank: string;
  victimIdentifier: string; destinationKnown: "yes" | "no"; destination: string; transactionType: string;
  evidence: EvidenceFile[];
  suspectMobile: string; suspectEmail: string; suspectUpi: string; suspectBank: string; suspectWebsite: string; suspectSocial: string; suspectPhone: string; suspectOther: string;
  fullName: string; mobile: string; email: string; state: string; district: string; policeStation: string;
};

const emptyDraft: ComplaintDraft = {
  incidentDate: "", incidentTime: "", fraudType: "UPI Fraud", fraudMethod: "Fraudulent Call", incidentDescription: "",
  transactionId: "", transactionDate: "", transactionTime: "", amount: "", bank: "", victimIdentifier: "", destinationKnown: "no", destination: "", transactionType: "UPI", evidence: [],
  suspectMobile: "", suspectEmail: "", suspectUpi: "", suspectBank: "", suspectWebsite: "", suspectSocial: "", suspectPhone: "", suspectOther: "",
  fullName: "", mobile: "", email: "", state: "Telangana", district: "Medchal-Malkajgiri", policeStation: "",
};

const steps = ["Incident", "Transaction", "Evidence", "Suspect", "Your Information"];
const fraudTypes = ["UPI Fraud", "Online Banking Fraud", "Credit/Debit Card Fraud", "Investment Fraud", "Job/Employment Fraud", "Phishing", "OTP Fraud", "Identity Theft", "Social Media Fraud", "E-commerce Fraud", "Other"];
const policeStations = ["Select police station", "Cyber Crime Police Station, Hyderabad", "Madhapur Police Station", "Kukatpally Police Station", "Malkajgiri Police Station", "Medchal Police Station"];

function Field({ label, value, onChange, required = false, type = "text", placeholder = "" }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; type?: string; placeholder?: string }) {
  return <label className="block text-sm font-semibold">{label}{required && <span className="ml-1 text-destructive">*</span>}<input type={type} required={required} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 h-11 w-full border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring" /></label>;
}
function SelectField({ label, value, onChange, options, required = false }: { label: string; value: string; onChange: (value: string) => void; options: string[]; required?: boolean }) {
  return <label className="block text-sm font-semibold">{label}{required && <span className="ml-1 text-destructive">*</span>}<select required={required} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 h-11 w-full border border-input bg-background px-3 text-sm"><option value="">Select {label.toLowerCase()}</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label>;
}
function TextAreaField({ label, value, onChange, required = false, placeholder = "" }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; placeholder?: string }) {
  return <label className="block text-sm font-semibold">{label}{required && <span className="ml-1 text-destructive">*</span>}<textarea required={required} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 min-h-32 w-full resize-y border border-input bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-ring" /></label>;
}
function Section({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) {
  return <section className="border border-border bg-card civic-shadow"><div className="border-b border-border px-5 py-4 sm:px-6"><h2 className="text-xl font-extrabold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{subtitle}</p></div><div className="space-y-5 p-5 sm:p-6">{children}</div></section>;
}

function IncidentStep({ draft, setField }: { draft: ComplaintDraft; setField: (key: keyof ComplaintDraft, value: string) => void }) {
  return <Section title="1. Incident Information" subtitle="Tell us what happened."><div className="grid gap-5 sm:grid-cols-2"><Field label="Incident date" type="date" value={draft.incidentDate} onChange={(value) => setField("incidentDate", value)} required /><Field label="Incident time" type="time" value={draft.incidentTime} onChange={(value) => setField("incidentTime", value)} required /><SelectField label="Fraud type" value={draft.fraudType} onChange={(value) => setField("fraudType", value)} options={fraudTypes} required /><SelectField label="How the fraud happened" value={draft.fraudMethod} onChange={(value) => setField("fraudMethod", value)} options={["Fraudulent Call", "Fake Website", "Phishing Link", "Fake App", "UPI Request", "OTP Sharing", "Social Media Contact", "Other"]} required /></div><TextAreaField label="Description of incident" value={draft.incidentDescription} onChange={(value) => setField("incidentDescription", value)} required placeholder="Describe what happened in your own words." /><p className="text-xs text-muted-foreground">You do not need to provide technical information here.</p></Section>;
}
function TransactionStep({ draft, setField }: { draft: ComplaintDraft; setField: (key: keyof ComplaintDraft, value: string) => void }) {
  return <Section title="2. Transaction Information" subtitle="Provide details about the financial transaction involved in the fraud."><div className="border-l-4 border-primary bg-muted p-3 text-sm">Your Transaction ID / UTR helps authorities trace the movement of funds.</div><div className="grid gap-5 sm:grid-cols-2"><Field label="Transaction ID / UTR" value={draft.transactionId} onChange={(value) => setField("transactionId", value)} required placeholder="Enter the reference if available" /><Field label="Transaction date" type="date" value={draft.transactionDate} onChange={(value) => setField("transactionDate", value)} required /><Field label="Transaction time" type="time" value={draft.transactionTime} onChange={(value) => setField("transactionTime", value)} required /><Field label="Fraud amount (INR)" type="number" value={draft.amount} onChange={(value) => setField("amount", value)} required placeholder="75000" /><Field label="Bank / wallet / merchant" value={draft.bank} onChange={(value) => setField("bank", value)} required /><Field label="Victim account / UPI identifier" value={draft.victimIdentifier} onChange={(value) => setField("victimIdentifier", value)} /><SelectField label="Transaction type" value={draft.transactionType} onChange={(value) => setField("transactionType", value)} options={["UPI", "Bank Transfer", "NEFT", "IMPS", "RTGS", "Card Payment", "Wallet", "ATM Withdrawal", "Other"]} required /></div><fieldset><legend className="text-sm font-semibold">Do you know the recipient/destination account or UPI ID?</legend><div className="mt-3 flex gap-5"><label className="flex items-center gap-2 text-sm"><input type="radio" checked={draft.destinationKnown === "yes"} onChange={() => setField("destinationKnown", "yes")} /> YES</label><label className="flex items-center gap-2 text-sm"><input type="radio" checked={draft.destinationKnown === "no"} onChange={() => setField("destinationKnown", "no")} /> NO</label></div></fieldset>{draft.destinationKnown === "yes" && <Field label="Destination account / UPI identifier" value={draft.destination} onChange={(value) => setField("destination", value)} />}<p className="text-xs text-muted-foreground">If you do not know the destination account or UPI ID, you can continue. You can upload a receipt or bank statement in the next step.</p></Section>;
}
function EvidenceStep({ draft, setField }: { draft: ComplaintDraft; setField: (key: keyof ComplaintDraft, value: EvidenceFile[]) => void }) {
  const addFiles = (files: FileList | null) => { if (!files) return; const next = Array.from(files).map((file) => ({ id: `${file.name}-${file.lastModified}`, name: file.name, type: file.type || "Document", size: `${Math.max(1, Math.round(file.size / 1024))} KB`, status: "Uploaded" as const })); setField("evidence", [...draft.evidence, ...next]); };
  const onDrop = (event: DragEvent<HTMLLabelElement>) => { event.preventDefault(); addFiles(event.dataTransfer.files); };
  return <Section title="3. Evidence" subtitle="Upload documents or screenshots that may help investigate your complaint."><label onDragOver={(event) => event.preventDefault()} onDrop={onDrop} className="block cursor-pointer border-2 border-dashed border-border bg-muted p-8 text-center hover:border-primary"><UploadCloud className="mx-auto text-primary" size={30}/><p className="mt-3 font-bold">Drag and drop files here</p><p className="mt-1 text-sm text-muted-foreground">or choose files from your device</p><input type="file" multiple className="sr-only" onChange={(event: ChangeEvent<HTMLInputElement>) => addFiles(event.target.files)} /></label><p className="text-xs text-muted-foreground">Supported categories include bank statements, transaction receipts, UPI/SMS/chat screenshots, emails, URLs, social profiles, call recordings, and other relevant documents.</p>{draft.evidence.length > 0 && <div className="space-y-2">{draft.evidence.map((file) => <div className="flex items-center gap-3 border border-border bg-background p-3" key={file.id}><Paperclip size={16} className="shrink-0 text-primary"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{file.name}</p><p className="text-xs text-muted-foreground">{file.type} · {file.size} · {file.status}</p></div><button type="button" aria-label={`Remove ${file.name}`} onClick={() => setField("evidence", draft.evidence.filter((item) => item.id !== file.id))} className="text-muted-foreground hover:text-destructive"><Trash2 size={16}/></button></div>)}</div>}<p className="border-l-4 border-accent bg-muted p-3 text-xs text-muted-foreground">Do not upload unnecessary personal information. No evidence available? You can continue and provide additional information later.</p></Section>;
}
function SuspectStep({ draft, setField }: { draft: ComplaintDraft; setField: (key: keyof ComplaintDraft, value: string) => void }) {
  return <Section title="4. Suspect Information" subtitle="Provide any information you have about the suspected person or account."><p className="border-l-4 border-accent bg-muted p-3 text-sm font-semibold">Optional - provide this information only if known.</p><div className="grid gap-5 sm:grid-cols-2"><Field label="Suspect mobile number" value={draft.suspectMobile} onChange={(value) => setField("suspectMobile", value)} /><Field label="Suspect email" type="email" value={draft.suspectEmail} onChange={(value) => setField("suspectEmail", value)} /><Field label="Suspect UPI ID" value={draft.suspectUpi} onChange={(value) => setField("suspectUpi", value)} /><Field label="Suspect bank account" value={draft.suspectBank} onChange={(value) => setField("suspectBank", value)} /><Field label="Website / URL" value={draft.suspectWebsite} onChange={(value) => setField("suspectWebsite", value)} /><Field label="Social media account" value={draft.suspectSocial} onChange={(value) => setField("suspectSocial", value)} /><Field label="Phone number" value={draft.suspectPhone} onChange={(value) => setField("suspectPhone", value)} /><Field label="Other identifier" value={draft.suspectOther} onChange={(value) => setField("suspectOther", value)} /></div><p className="text-sm text-muted-foreground">Don't know who the suspect is? That's okay. You can continue without providing these details.</p></Section>;
}
function VictimStep({ draft, setField }: { draft: ComplaintDraft; setField: (key: keyof ComplaintDraft, value: string) => void }) {
  return <Section title="5. Your Information" subtitle="Provide your details so authorities can contact you regarding your complaint."><div className="grid gap-5 sm:grid-cols-2"><Field label="Full name" value={draft.fullName} onChange={(value) => setField("fullName", value)} required /><Field label="Mobile number" type="tel" value={draft.mobile} onChange={(value) => setField("mobile", value)} required placeholder="10-digit mobile number" /><Field label="Email address" type="email" value={draft.email} onChange={(value) => setField("email", value)} required /><SelectField label="State" value={draft.state} onChange={(value) => setField("state", value)} options={["Telangana", "Andhra Pradesh", "Karnataka", "Other"]} required /><SelectField label="District" value={draft.district} onChange={(value) => setField("district", value)} options={["Medchal-Malkajgiri", "Hyderabad", "Rangareddy", "Warangal", "Nizamabad"]} required /><SelectField label="Police station" value={draft.policeStation} onChange={(value) => setField("policeStation", value)} options={policeStations.slice(1)} required /></div></Section>;
}

function ReviewRow({ label, value }: { label: string; value: string }) { return <div className="flex flex-col gap-1 border-b border-border py-2 text-sm sm:flex-row sm:justify-between"><dt className="text-muted-foreground">{label}</dt><dd className="font-semibold sm:max-w-[65%] sm:text-right">{value || "Not provided"}</dd></div>; }
function ReviewCard({ title, onEdit, children }: { title: string; onEdit: () => void; children: ReactNode }) { return <section className="border border-border bg-card p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-bold">{title}</h2><Button type="button" size="sm" variant="outline" onClick={onEdit}>Edit</Button></div><dl className="mt-3">{children}</dl></section>; }
function Review({ draft, onEdit, onSubmit }: { draft: ComplaintDraft; onEdit: (step: number) => void; onSubmit: () => void }) {
  const [confirmed, setConfirmed] = useState(false);
  return <PageShell eyebrow="Review before submission" title="Review Your Complaint"><div className="space-y-4"><ReviewCard title="Incident Information" onEdit={() => onEdit(1)}><ReviewRow label="Fraud type" value={draft.fraudType}/><ReviewRow label="Date and time" value={`${draft.incidentDate} ${draft.incidentTime}`}/><ReviewRow label="Description" value={draft.incidentDescription}/></ReviewCard><ReviewCard title="Transaction Information" onEdit={() => onEdit(2)}><ReviewRow label="Transaction ID / UTR" value={draft.transactionId}/><ReviewRow label="Amount" value={draft.amount ? `₹${Number(draft.amount).toLocaleString("en-IN")}` : ""}/><ReviewRow label="Bank / wallet / merchant" value={draft.bank}/><ReviewRow label="Destination" value={draft.destinationKnown === "yes" ? draft.destination : "Not known"}/></ReviewCard><ReviewCard title="Evidence" onEdit={() => onEdit(3)}><ReviewRow label="Files" value={draft.evidence.length ? draft.evidence.map((file) => file.name).join(", ") : "No evidence uploaded"}/></ReviewCard><ReviewCard title="Suspect Information" onEdit={() => onEdit(4)}><ReviewRow label="Information" value={draft.suspectMobile || draft.suspectEmail || draft.suspectUpi || "No information provided"}/></ReviewCard><ReviewCard title="Victim Information" onEdit={() => onEdit(5)}><ReviewRow label="Name" value={draft.fullName}/><ReviewRow label="Contact" value={`${draft.mobile} · ${draft.email}`}/><ReviewRow label="Location" value={`${draft.district}, ${draft.state}`}/></ReviewCard><label className="flex items-start gap-3 border border-border bg-muted p-4 text-sm"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} className="mt-0.5 size-4"/> <span>I confirm that the information provided is accurate to the best of my knowledge.</span></label><Button type="button" disabled={!confirmed} onClick={onSubmit}>Submit Complaint<ArrowRight/></Button></div></PageShell>;
}
function PageShell({ eyebrow, title, children }: { eyebrow: string; title: string; children: ReactNode }) { return <main className="mx-auto min-h-[700px] max-w-[1100px] px-4 py-8 sm:px-6"><div className="mb-7"><p className="text-xs font-bold uppercase text-primary">{eyebrow}</p><h1 className="mt-1 text-2xl font-extrabold sm:text-3xl">{title}</h1></div>{children}</main>; }

export function ComplaintWizard({ profile, onCancel, onSubmitted, onTrack }: { profile: CitizenProfile | null; onCancel: () => void; onSubmitted: (complaint: CitizenComplaint) => void; onTrack: () => void }) {
  const [draft, setDraft] = useState<ComplaintDraft>({ ...emptyDraft, fullName: profile?.full_name ?? "", mobile: profile?.phone ?? "", email: profile?.email ?? "" });
  const [step, setStep] = useState(1);
  const [reviewing, setReviewing] = useState(false);
  const [submitted, setSubmitted] = useState<CitizenComplaint | null>(null);
  const [error, setError] = useState("");
  const setField = (key: keyof ComplaintDraft, value: string | EvidenceFile[]) => setDraft((current) => ({ ...current, [key]: value }));
  const validateStep = () => {
    if (step === 1 && (!draft.incidentDate || !draft.incidentTime || !draft.fraudType || !draft.incidentDescription.trim())) return "Please complete the incident date, time, fraud type, and description.";
    if (step === 2 && (!draft.transactionId.trim() || !draft.transactionDate || !draft.transactionTime || !draft.amount || Number(draft.amount) <= 0 || !draft.bank.trim() || !draft.transactionType)) return "Please complete the transaction ID / UTR, date, time, amount, bank or wallet, and transaction type.";
    if (step === 5 && (!draft.fullName.trim() || !/^[0-9]{10}$/.test(draft.mobile.replace(/\D/g, "")) || !draft.email.trim() || !draft.state || !draft.district || !draft.policeStation)) return "Please enter a valid 10-digit mobile number and complete your contact details.";
    return "";
  };
  const next = () => { const validation = validateStep(); if (validation) { setError(validation); return; } setError(""); if (step === 5) setReviewing(true); else setStep(step + 1); };
  const submit = () => { const now = new Date(); const id = `NCRP-TG-${now.getFullYear()}-${String(now.getTime()).slice(-6)}`; const complaint: CitizenComplaint = { id, type: draft.fraudType, submitted: now.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }), updated: now.toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }), status: "Investigation in Progress", actionRequired: false }; setSubmitted(complaint); onSubmitted(complaint); };
  if (submitted) return <PageShell eyebrow="Complaint submitted" title="Complaint Submitted Successfully"><div className="mx-auto max-w-2xl border border-border bg-card p-8 text-center civic-shadow"><CheckCircle2 className="mx-auto text-emerald-600" size={52}/><h2 className="mt-4 text-xl font-extrabold">Your cybercrime complaint has been registered.</h2><p className="mt-5 text-sm text-muted-foreground">Acknowledgement number</p><p className="mt-1 break-all text-2xl font-extrabold text-primary">{submitted.id}</p><div className="mx-auto mt-6 max-w-sm space-y-2 text-left text-sm"><ReviewRow label="Complaint type" value={submitted.type}/><ReviewRow label="Submitted" value={submitted.submitted}/><ReviewRow label="Status" value="Complaint Submitted"/></div><p className="mt-5 text-sm text-muted-foreground">Please keep this acknowledgement number for future reference.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Button onClick={onTrack}>Track Complaint<ArrowRight/></Button><Button variant="outline" onClick={() => window.print()}><Printer/>Download / Print Acknowledgement</Button></div></div></PageShell>;
  if (reviewing) return <Review draft={draft} onEdit={(selectedStep) => { setReviewing(false); setStep(selectedStep); }} onSubmit={submit}/>;
  return <PageShell eyebrow="Citizen services" title="Register a Cybercrime Complaint"><div className="mb-6 grid gap-2 sm:grid-cols-5">{steps.map((label, index) => { const number = index + 1; const complete = number < step; const active = number === step; return <button type="button" key={label} disabled={number > step} onClick={() => { if (number <= step) { setError(""); setStep(number); } }} className={`border p-3 text-left text-xs font-bold ${active ? "border-primary bg-primary text-primary-foreground" : complete ? "border-primary bg-muted text-primary" : "border-border bg-card text-muted-foreground"}`}><span className="flex items-center gap-2">{complete ? <Check size={14}/> : <span>{number}</span>}{label}</span></button>; })}</div>{step === 1 && <IncidentStep draft={draft} setField={setField}/>} {step === 2 && <TransactionStep draft={draft} setField={setField}/>} {step === 3 && <EvidenceStep draft={draft} setField={setField}/>} {step === 4 && <SuspectStep draft={draft} setField={setField}/>} {step === 5 && <VictimStep draft={draft} setField={setField}/>} {error && <p className="mt-4 border-l-4 border-destructive bg-muted p-3 text-sm text-destructive" role="alert">{error}</p>}<div className="mt-5 flex flex-wrap justify-between gap-3"><Button type="button" variant="outline" onClick={() => step === 1 ? onCancel() : setStep(step - 1)}><ArrowLeft/>{step === 1 ? "Cancel" : "Back"}</Button><Button type="button" onClick={next}>{step === 5 ? "Review Complaint" : "Save & Continue"}<ArrowRight/></Button></div></PageShell>;
}
