"""Add citizen profiles

Revision ID: 05a1786d3245
Revises: d104cbd9f7af
Create Date: 2026-09-18 07:35:23.770445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a1786d3245'
down_revision: Union[str, Sequence[str], None] = 'd104cbd9f7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('identity_type', sa.String(), nullable=False),
    sa.Column('identity_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_profiles_email'), 'citizen_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_citizen_profiles_id'), 'citizen_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citizen_profiles_id'), table_name='citizen_profiles')
    op.drop_index(op.f('ix_citizen_profiles_email'), table_name='citizen_profiles')
    op.drop_table('citizen_profiles')
    # ### end Alembic commands ###
